"""Reviewed public copy for the current local-only 0.1.0 implementation.

HTML in this module is developer-authored, not user input. Contact and links are
inserted by build.py from config.json. Do not publish future capabilities as facts.
"""

PRIVACY = {
"zh": [
("scope", "适用范围与开发者", '''<p>本政策适用于“轻一点”（英文品牌 Lighter，中文完整名称“轻一点：你的减重教练”）当前本机版本、官方网站和技术支持服务。开发与维护方为轻一点开发者，GitHub 账户为 <a href="{repo_owner}">weizhichao1027-collab</a>，联系邮箱为 <a href="mailto:{email}">{email}</a>。</p><p>本政策根据当前 0.1.0 版本的实际功能编写。App 正在准备发布，当前尚未提供 App Store 下载链接。官网展示的界面来自开发版本，使用示例或测试资料。新功能如涉及新的数据处理，会在启用前更新说明，并在需要时取得你的许可。</p><p>App、浏览本网站和主动联系支持是不同的使用场景，下文分别说明其数据处理范围。</p>'''),
("local-data", "App 在本机处理哪些信息", '''<p>你主动输入的信息仅用于设备上的记录、计划和回顾。可能涉及的内容如下；具体字段取决于你使用的功能。健康相关信息具有敏感性，请仅填写使用该功能所需的信息。</p><div class="table-scroll" tabindex="0" role="region" aria-label="本机数据类别、用途与位置"><table class="policy-table"><thead><tr><th scope="col">数据类别</th><th scope="col">用途</th><th scope="col">处理位置</th></tr></thead><tbody><tr><td>入门资料与安全筛查</td><td>你填写的愿望、困难、健康和生活情况、年龄范围、身高或测量信息、习惯与限制，以及未完成的入门草稿，用于确认适合范围与生成本机计划。</td><td>App 私有本机存储</td></tr><tr><td>体重与测量记录</td><td>你输入的数值、单位、时间及相关说明，用于记录历史与条件性趋势展示。</td><td>App 私有本机存储</td></tr><tr><td>饮食、活动与行动记录</td><td>餐食描述、选择与感受、活动日期和时长、主观感受、行动状态及备注，用于日常记录与回顾。</td><td>App 私有本机存储</td></tr><tr><td>计划与使用状态</td><td>计划及历史、周复盘、安全事件、暂停状态、演示进度，用于保持使用连续性和异常恢复。演示进度与真实活动分别记录。</td><td>App 私有本机存储</td></tr><tr><td>偏好与本机环境</td><td>语言、显示单位、教练语气、提醒时间、时区与日期格式，用于界面显示与本机提醒。语言偏好保存在系统 UserDefaults 中。</td><td>App 本机存储 / 系统偏好</td></tr></tbody></table></div><p>本机规则基于你输入的资料生成提示、计划和回顾；当前不调用云端 AI，也不会将记录发送给开发者。我们无法从远程查看、修改或代你恢复设备中的记录。</p>'''),
("collection", "上传、追踪与第三方 SDK", '''<p>当前 App 不设账户，不提供后台服务器或云端健康数据库，不上传你的健康记录。没有广告、广告标识符访问、第三方统计分析、会话回放、第三方 AI 调用或跨 App 追踪；没有出售或用于定向广告的数据处理。</p><p>当前未接入 Apple 健康 / HealthKit、CloudKit、社交登录、支付或订阅 SDK。App 核心记录与本机规则可离线使用。你主动打开官网、参考资料或外部链接时，浏览器会连接对应的网站，其处理方式见本政策第 7 节。</p>'''),
("permissions", "系统权限与可选功能", '''<p><strong>通知权限：</strong>只有你在 App 的提醒设置中主动启用并保存提醒时，才会申请系统通知权限。提醒在设备本地安排；锁屏文字不包含体重或减重目标。你可以在 App 内关闭提醒，或在 iOS 系统设置中撤回通知权限，继续使用手动记录。</p><p><strong>文件导出：</strong>你主动选择“导出我的本机记录”后，由系统文件选择器让你决定保存位置。当前 App 不要求访问通讯录、相机、麦克风、照片资料库、定位或 Apple 健康数据。</p><p>权限可在 iOS“设置”中管理。撤回通知权限不会删除已有记录；删除记录使用 App 内的数据管理入口。</p>'''),
("storage", "保存期限、安全与恢复", '''<p>健康记录保存在 App 的私有沙盒目录。健康记录文件启用 iOS 文件保护，并标记为不进入设备备份；保存后进行回读核对，同时保留一份本机上一版本用于异常恢复。必要时可能保留恢复副本或会话状态标记。这些机制属于本机存储，不提供云端同步或远程恢复。</p><p>记录在设备上保留，直到你编辑、删除相关记录、执行全部本机清理，或系统移除 App 及其数据。语言偏好单独保存在系统偏好中，可能在删除健康记录后仍保留。系统的卸载、备份或设备迁移行为受 iOS 管理，不能据此保证健康记录可迁移。</p><p>请使用设备锁屏与系统安全设置，并妥善保管导出文件。任何存储与传输方式都无法保证绝对安全；当前仍需完成真机存储保护、通知等验证。设备丢失、损坏、卸载 App 或删除数据可能导致记录无法恢复。</p>'''),
("control", "你的查看、修改、导出与删除选择", '''<p>你可以在 App 中查看和编辑已有记录、删除支持单条删除的记录，并在“设置 → 数据与连接”中选择“导出我的本机记录”或“删除全部本机记录”。导出格式为 JSON，可能包含筛查、体重、餐食、活动、计划与设置等敏感内容。</p><p>全部删除会清理并核对主记录、上一版本、恢复副本和会话标记。若清理未完成，App 会提示剩余项目并提供重试。请以 App 中的核验结果为准；完成后，App 不提供恢复这些已删除记录的功能。</p><p><strong>外部副本：</strong>你自行导出到“文件”、iCloud Drive、其他云盘或发送给他人的文件，不会随 App 内的删除自动清除。系统也可能管理导出暂存。请到对应位置分别删除或管理这些副本。当前版本没有导入 JSON 恢复记录的入口。</p><p>你可以停止使用并移除 App。开发者未持有你的本机记录，因此无法替你远程访问、删除或恢复它们。</p>'''),
("website", "官网、GitHub 与外部服务", '''<p>本网站由 GitHub Pages 托管。网站代码不设置 Cookie，不使用 localStorage，不加入访问统计、广告像素、外部字体、第三方视频或聊天嵌入；图片与脚本均随本站提供。FAQ 搜索、界面切换和复制反馈模板在浏览器本地运行，不发送到开发者服务器。</p><p>GitHub 作为托管服务商，会为安全目的记录和保存访客 IP 地址，即使访客没有登录 GitHub；其基础设施还可能处理请求相关信息。该处理由 GitHub 管理，详见 <a href="https://docs.github.com/en/pages/getting-started-with-github-pages/what-is-github-pages#data-collection" rel="noopener noreferrer">GitHub Pages 数据收集说明</a>与 <a href="https://docs.github.com/en/site-policy/privacy-policies/github-general-privacy-statement" rel="noopener noreferrer">GitHub 隐私声明</a>。我们没有添加独立访问分析。</p><p>你点击邮件链接后，将使用你选择的邮件服务；打开 GitHub 问题页面、Apple 页面或 App 内参考资料链接后，相关服务按各自政策处理请求。外部链接不会自动携带你的 App 健康记录。GitHub Issues 为公开渠道，请勿发布真实健康记录、筛查答案、导出文件或未打码截图。</p><p>支持页搜索词和打开的 FAQ 会显示在页面地址中。不要在搜索栏输入健康资料或个人身份信息；复制页面地址时也请检查其中的查询内容。</p>'''),
("support-data", "主动联系支持时的信息", '''<p>发送支持邮件或提交问题时，我们会收到你主动提供的邮箱地址 / GitHub 账户、邮件或问题内容、App 与系统版本，以及你选择附上的截图等。用于回复、排查技术问题、处理隐私请求及维护相关处理记录，不用于营销、广告或 AI 训练。</p><p>请使用示例数据描述问题，遮盖个人信息，不要默认发送完整健康记录或 JSON 导出文件。若排查确实需要更多信息，我们会先说明用途与所需最小范围，由你决定是否提供。</p><p>支持通信仅在完成请求、必要后续排查以及适用法律要求所需期间保留；不再需要时删除或去除可识别信息。你可以通过 <a href="mailto:{email}">{email}</a>请求访问、更正或删除我们持有的支持信息，或撤回基于同意的处理。我们会根据请求与适用规则处理；依法必须保留的信息会说明原因。GitHub 或邮件服务商管理的副本，需按其渠道与规则处理。</p>'''),
("sharing", "共享与跨境处理", '''<p>当前 App 不把本机健康记录分享给开发者、广告商或第三方，也不自动将健康记录跨境传输。你自主导出文件、选择云盘或向他人发送记录时，相关数据会由你选择的接收方处理。</p><p>网站托管与支持邮件使用 GitHub、邮件服务等外部基础设施，请求或你主动提交的内容可能在你的所在国家或地区以外处理。处理地点、保存及保障措施以相关服务商政策为准。不要通过公开 GitHub 渠道提交敏感信息。</p><p>我们不会出售支持信息。仅在处理请求所必需的服务提供商范围内，或依法需要履行义务、保护合法权益时处理或披露所持有的信息，并限制在必要范围。</p>'''),
("adults", "成年人使用与健康边界", '''<p>轻一点的体重管理功能面向 18 岁及以上成年人，不面向儿童或未成年人提供减重计划。App 提供一般习惯支持和记录，不提供诊断、治疗、医疗建议或疗效保证，也不能替代专业医疗人员。</p><p>开发者不主动收集未成年人的健康资料。如果你认为我们在支持通信中收到未成年人的个人信息，请联系支持邮箱，我们会核实并处理。关于 App 的适合范围与暂停提示，请遵循 App 中的说明。</p>'''),
("changes", "政策更新与联系方式", '''<p>本政策的更新日期及适用版本显示在页首。数据处理或功能发生变化时，我们会更新此页面；涉及重大变化或需要许可的处理时，会在启用前通过合适方式提示。此前的政策版本可在 <a href="{repo}/commits/main/" rel="noopener noreferrer">GitHub 更新记录</a>中查看。</p><p>对隐私、数据管理或本政策有疑问，请联系 <a href="mailto:{email}?subject=Lighter%20privacy%20request">{email}</a>，或查看 <a href="{support}">技术支持页面</a>。请说明请求类型和使用场景，无需提供全部健康记录。</p>''')],
"en": [
("scope", "Scope and developer", '''<p>This policy covers the current local version of Lighter (Chinese name: 轻一点 / 轻一点：你的减重教练), its official website, and technical support. The service is maintained by the Lighter developer, GitHub account <a href="{repo_owner}">weizhichao1027-collab</a>. Contact: <a href="mailto:{email}">{email}</a>.</p><p>This policy describes the implemented features in version 0.1.0. The app is being prepared for release and has no App Store download link yet. Website screenshots show development builds with example or test data. We will explain new processing and obtain permission where required before enabling relevant new features.</p><p>Using the app, visiting this website, and contacting support are separate situations. Their data practices are described separately below.</p>'''),
("local-data", "Information processed on your device", '''<p>Information you enter is used on your device for records, plans, and reviews. The categories below depend on which features you use. Health information is sensitive; provide only what you need for the feature.</p><div class="table-scroll" tabindex="0" role="region" aria-label="Local information, purposes and storage"><table class="policy-table"><thead><tr><th scope="col">Category</th><th scope="col">Purpose</th><th scope="col">Location</th></tr></thead><tbody><tr><td>Onboarding and screening</td><td>Your goals, difficulties, health and daily circumstances, age range, height or measurements, habits, limitations, and unfinished drafts help determine the applicable scope and create local plans.</td><td>Private app storage</td></tr><tr><td>Weight and measurements</td><td>Values, original units, dates and notes support history and conditional trend displays.</td><td>Private app storage</td></tr><tr><td>Meals, activities and actions</td><td>Meal descriptions, choices and feelings, activity dates and durations, perceived effort, action status and notes support daily records and reviews.</td><td>Private app storage</td></tr><tr><td>Plans and app state</td><td>Plans and history, weekly reviews, safety events, pauses and demonstration progress support continuity and recovery. Demonstrations are stored separately from actual activity.</td><td>Private app storage</td></tr><tr><td>Preferences and local context</td><td>Language, display units, coaching tone, reminder time, time zone and date formatting support presentation and local reminders. Language preferences use system UserDefaults.</td><td>Local app / system preferences</td></tr></tbody></table></div><p>Local rules use your entries to generate prompts, plans and reviews. The current app does not call cloud AI or send your records to the developer. We cannot remotely view, change or recover records on your device.</p>'''),
("collection", "Uploads, tracking and third-party SDKs", '''<p>The current app has no account system, backend server or cloud health database and does not upload your health records. It contains no ads, advertising identifier access, third-party analytics, session replay, third-party AI calls or cross-app tracking. It does not sell data or process data for targeted advertising.</p><p>Apple Health / HealthKit, CloudKit, social sign-in, payments and subscription SDKs are not integrated. Core records and local rules work offline. Opening the website, references or external links connects your browser to those websites; see section 7.</p>'''),
("permissions", "System permissions and optional features", '''<p><strong>Notifications:</strong> The app requests system notification permission only when you explicitly enable and save reminders. Reminders are scheduled on your device. Lock-screen messages do not include your weight or weight goals. You can turn reminders off in the app or revoke notification permission in iOS Settings while continuing manual records.</p><p><strong>File export:</strong> After you choose to export your local records, the system file picker lets you choose the destination. The current app does not request contacts, camera, microphone, photo library, location or Apple Health permissions.</p><p>Manage system permissions in iOS Settings. Revoking notification permission does not delete records; use the app’s data controls to delete them.</p>'''),
("storage", "Retention, protection and recovery", '''<p>Health records are stored in the app’s private sandbox. Record files use iOS file protection and are marked to be excluded from device backups. Saved data is read back for verification; one previous local version is retained for recovery. A recovery copy or session-state marker may also be retained when needed. These are local mechanisms and do not provide cloud sync or remote recovery.</p><p>Records remain on the device until you edit or delete them, clear all local records, or the system removes the app and its data. Language preferences are stored separately and may remain after health records are deleted. iOS manages offloading, backups and device migration; these do not guarantee that your health records can be transferred.</p><p>Use device locking and system security settings, and protect exported files. No storage or transfer method is absolutely secure. Device testing of storage protection, notifications and other behavior still needs completion. Device loss, damage, uninstalling the app or deleting data may make records unrecoverable.</p>'''),
("control", "Access, edit, export and delete", '''<p>You can view and edit records, delete individual records where supported, and choose “Export my local records” or “Delete all local records” under Settings → Data and connections. JSON exports may contain sensitive screening answers, weight, meals, activities, plans and preferences.</p><p>Deleting all local records clears and verifies the main records, previous version, recovery copy and session marker. If cleanup is incomplete, the app reports remaining items and offers retry. Rely on the app’s verification result. Once deletion is complete, the app does not provide recovery of those deleted records.</p><p><strong>External copies:</strong> Files you export to Files, iCloud Drive, other cloud storage or other people are not removed when you delete records inside the app. The system may also manage temporary export copies. Manage those copies separately at their destinations. The current version has no JSON import / restore feature.</p><p>You can stop using and remove the app. The developer does not hold your local records and cannot remotely access, delete or recover them for you.</p>'''),
("website", "Website, GitHub and external services", '''<p>This website is hosted on GitHub Pages. Our website code sets no cookies, uses no localStorage, and includes no analytics, ad pixels, external fonts, embedded third-party videos or chat widgets. Images and scripts are served with the website. FAQ search, screenshot switching and copying the support template run in your browser without being sent to a developer server.</p><p>GitHub, the hosting provider, logs and stores visitors’ IP addresses for security, including when visitors are not signed in. Its infrastructure may also process request information. GitHub manages that processing; see the <a href="https://docs.github.com/en/pages/getting-started-with-github-pages/what-is-github-pages#data-collection" rel="noopener noreferrer">GitHub Pages data collection notice</a> and <a href="https://docs.github.com/en/site-policy/privacy-policies/github-general-privacy-statement" rel="noopener noreferrer">GitHub Privacy Statement</a>. We have added no separate visitor analytics.</p><p>Email links open your chosen mail service. GitHub issue pages, Apple pages and the app’s reference links follow their own policies. External links do not automatically include your app health records. GitHub Issues are public: do not post health records, screening answers, export files or unredacted screenshots.</p><p>Support search terms and opened FAQs appear in the page URL. Do not enter health details or identifying information into the search field, and check query text before sharing a link.</p>'''),
("support-data", "Information you send to support", '''<p>When you email support or submit an issue, we receive the email address or GitHub account, message contents, app and system versions, and screenshots or other material you choose to send. We use them to reply, troubleshoot, handle privacy requests and keep necessary resolution records, not for marketing, advertising or AI training.</p><p>Use example data and redact personal information. Do not send complete health records or JSON exports by default. If troubleshooting needs more information, we will explain the purpose and minimum scope first so you can decide whether to provide it.</p><p>Support correspondence is retained only as needed to resolve the request, perform necessary follow-up and meet applicable legal requirements; identifiable information is deleted or removed when no longer needed. Email <a href="mailto:{email}">{email}</a> to request access, correction or deletion of support information we hold, or withdraw consent-based processing. We will handle requests under applicable rules and explain legally required retention. Copies managed by GitHub or mail providers are subject to their own controls.</p>'''),
("sharing", "Sharing and international processing", '''<p>The current app does not share local health records with the developer, advertisers or third parties and does not automatically transfer health records internationally. When you choose to export files, select cloud storage or send records to someone, your chosen recipient processes that information.</p><p>Website hosting and support email use infrastructure such as GitHub and mail services. Requests or content you submit may be processed outside your country or region. Provider policies describe their locations, retention and safeguards. Do not use public GitHub channels for sensitive information.</p><p>We do not sell support information. Information we hold is processed or disclosed only to necessary service providers to handle requests, or as required by law or to protect lawful rights, limited to what is necessary.</p>'''),
("adults", "Adults and health limitations", '''<p>Lighter’s weight-management features are intended for adults aged 18 and over, not children or minors. The app provides general habit support and records, not diagnosis, treatment, medical advice or guaranteed outcomes, and cannot replace qualified healthcare professionals.</p><p>The developer does not intentionally collect minors’ health information. If you believe support correspondence contains a minor’s personal information, contact us so we can review and address it. Follow the app’s guidance about suitability and pauses.</p>'''),
("changes", "Updates and contact", '''<p>The policy date and applicable version appear at the top of this page. We will update the page when features or processing change, and provide appropriate notice before material changes or processing that requires permission. Previous policy versions are available in the <a href="{repo}/commits/main/" rel="noopener noreferrer">GitHub history</a>.</p><p>For privacy, data-management or policy questions, email <a href="mailto:{email}?subject=Lighter%20privacy%20request">{email}</a> or visit <a href="{support}">technical support</a>. Describe the request and situation; you do not need to provide complete health records.</p>''')]
}

FAQ = {
"zh": [
("download", "现在可以下载轻一点吗？", "当前正在准备发布，尚未提供 App Store 下载链接。官网展示当前开发版本的实际界面，专业内容审核与真机验收仍在进行。上线后，官网将提供经过确认的下载入口。请勿从未知来源安装同名应用。"),
("offline", "需要注册账号或联网吗？", "当前不需要账号。手动记录、计划和本机规则可离线使用；访问官网、参考资料或发送邮件需要网络。记录只存于当前设备，当前没有多设备同步或云端恢复。"),
("save", "输入后没有出现“已保存”，怎么办？", "排队或正在处理不等于已经保存。请留意页面中的保存回执与错误提示，保留当前输入，并按提示重试。设置中的“未完成的保存”会显示尚未可靠写入的项目。排查前不要卸载 App 或删除数据；如果问题持续，请用示例数据说明操作步骤并联系支持。"),
("export", "怎样导出我的记录？", "<ol><li>进入 App“设置 → 数据与连接”。</li><li>选择“导出我的本机记录”，查看并确认导出内容。</li><li>在系统文件选择器中选择保存位置，等待完成提示。</li></ol><p>导出为 JSON，包含健康相关记录，请妥善保管。选择云盘时，文件会由对应云服务处理。系统取消或未完成，不代表文件已经保存。</p>"),
("delete", "怎样删除数据？导出的文件会一起删除吗？", "在 App“设置 → 数据与连接”中选择“删除全部本机记录”，按提示确认并查看核验结果。若部分清理失败，请使用“重试剩余本机清理”。删除完成后无法在 App 中恢复。已导出的文件、邮件附件或其他 App 中的副本不会自动删除，请到原位置单独处理。语言偏好可能仍保留。"),
("recovery", "换手机、卸载或误删后能恢复吗？", "当前没有云端同步、账号恢复或 JSON 导入功能，健康记录文件被标记为不进入设备备份。本机“上一版本”只用于当前设备上的异常恢复，不是云备份。已有记录时，请先导出你希望保留的副本；导出可用于留存和查看，但当前不能承诺重新导入。不要把卸载重装作为首选排查方法。"),
("reminders", "为什么没有收到提醒？", "先检查 App“设置 → 本机提醒”中的偏好和当前状态，再检查 iOS“设置 → 通知 → 轻一点”是否允许通知。提醒还可能受系统专注模式、通知设置或 App 暂停与安全状态影响。提醒关闭或未送达时，手动记录仍可使用。当前实际送达还需完成真机验收。"),
("weight", "怎样切换语言或体重单位？", "在 App 设置的“日常偏好”中选择语言和体重显示单位。语言可跟随系统或手动选择；当前语言目录包括 13 种语言。改变显示单位不会改写原始测量值。若遇到翻译或格式问题，请提供页面名称、所选语言和示例内容。"),
("trend", "为什么体重趋势暂时没有结论？", "趋势展示取决于真实记录覆盖情况。资料不足或条件不满足时，App 会说明不确定性，而不会给出确定方向或精确达标日期。你可以在“进展”查看原始记录并核对输入；单次波动不能单独作为健康结论。"),
("activity", "运动演示会算入真实活动吗？", "不会。当前演示用于验证交互，演示进度与自主活动记录分开保存，不计入真实活动时长或行动完成。它不能作为动作教学；相关内容仍需专业审核。自主活动请通过对应记录入口填写实际情况。"),
("health", "轻一点能代替医生或营养师吗？", "不能。当前是面向成年人的一般习惯支持和记录工具，不提供诊断、治疗、个体医疗处方或效果保证。请遵循 App 的适合范围和暂停提示。技术支持处理产品问题，不能提供医疗判断；紧急健康问题请联系当地医疗或急救服务。"),
("payment", "当前有订阅、支付或 Apple 健康连接吗？", "当前版本没有订阅或支付，也未接入 Apple 健康 / HealthKit、云端 AI、第三方分析或广告。将来若新增相关功能，我们会在启用前更新功能与隐私说明。")],
"en": [
("download", "Can I download Lighter now?", "Lighter is being prepared for release and does not have an App Store link yet. Website images show actual development builds; professional content review and device acceptance are still in progress. We will add a verified download link when available. Avoid installing similarly named apps from unknown sources."),
("offline", "Do I need an account or internet connection?", "No account is needed in the current version. Manual records, plans and local rules work offline. Visiting websites or references and sending email requires internet access. Records stay on the current device; there is no multi-device sync or cloud recovery."),
("save", "My entry does not show as saved. What should I do?", "Queued or processing does not mean saved. Check the receipt and error shown on the page, keep your entry and retry as instructed. Settings lists incomplete saves that have not been reliably written. Do not uninstall the app or delete data before troubleshooting. If it persists, describe the steps using example data and contact support."),
("export", "How do I export my records?", "<ol><li>Open Settings → Data and connections.</li><li>Choose to export your local records and confirm the contents.</li><li>Choose a destination in the system file picker and wait for confirmation.</li></ol><p>Exports are JSON files containing sensitive health-related records. Protect them. A cloud destination is managed by that cloud provider. A canceled or unfinished system dialog does not confirm the file was saved.</p>"),
("delete", "How do I delete data? Are exports also removed?", "Choose to delete all local records under Settings → Data and connections, confirm, and check the verification result. If cleanup partly fails, retry remaining cleanup. Completed deletion cannot be recovered in the app. Exported files, email attachments and copies in other apps remain until you remove them separately. Language preferences may remain."),
("recovery", "Can I recover records after changing phones or uninstalling?", "There is no cloud sync, account recovery or JSON import. Health record files are marked to be excluded from device backups. The previous local version is for recovery on the same device, not a cloud backup. Export a copy you wish to keep before removing data. Exports preserve information for viewing but cannot currently be reimported. Do not use reinstalling as the first troubleshooting step."),
("reminders", "Why did I not receive a reminder?", "Check preferences and status under the app’s reminder settings, then check iOS Settings → Notifications → Lighter. Focus modes, system notification settings and the app’s pause or safety state may affect delivery. Manual records remain available without reminders. Actual delivery still needs device acceptance testing."),
("weight", "How do I change language or weight units?", "Choose language and display units in the app’s everyday preferences. Language can follow the system or be selected manually; the current catalog contains 13 languages. Changing display units does not rewrite original measurements. For translation or formatting issues, include the page name, selected language and example text."),
("trend", "Why is there no weight-trend conclusion yet?", "Trend displays depend on coverage of actual records. When data or conditions are insufficient, the app explains uncertainty rather than a definite direction or precise goal date. Review original entries under Progress. A single change is not a health conclusion on its own."),
("activity", "Does a movement demonstration count as real activity?", "No. Current demonstrations validate interactions; their progress is stored separately from self-recorded activities and does not count as real duration or action completion. They are not exercise instruction and still require professional review. Use the activity record entry for actual activity."),
("health", "Can Lighter replace a healthcare professional?", "No. It provides general habit support and records for adults, not diagnosis, treatment, personalized medical prescriptions or guaranteed results. Follow the app’s suitability and pause guidance. Technical support cannot provide medical judgment. For urgent health concerns, contact local medical or emergency services."),
("payment", "Are there subscriptions, payments or Apple Health connections?", "The current version has no subscriptions or payments and does not integrate Apple Health / HealthKit, cloud AI, third-party analytics or ads. We will update feature and privacy information before enabling relevant new capabilities.")]
}
